# Generated by Django 5.2.5 on 2026-03-27 14:00

import AI_Resume_Screening_App.resumes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkResumeUpload",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("processed_files", models.PositiveIntegerField(default=0)),
                ("failed_files", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_uploads",
                        to="users.company",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bulk_resume_uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "candidate_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "candidate_email",
                    models.EmailField(blank=True, db_index=True, max_length=254),
                ),
                ("candidate_phone", models.CharField(blank=True, max_length=30)),
                ("candidate_location", models.CharField(blank=True, max_length=255)),
                ("candidate_linkedin", models.URLField(blank=True)),
                ("candidate_github", models.URLField(blank=True)),
                ("candidate_website", models.URLField(blank=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=AI_Resume_Screening_App.resumes.models.resume_upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=10)),
                ("file_size_kb", models.PositiveIntegerField(default=0)),
                ("raw_text", models.TextField(blank=True)),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
                (
                    "highest_education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "High School"),
                            ("associate", "Associate Degree"),
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("mba", "MBA"),
                            ("phd", "PhD / Doctorate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("education_details", models.JSONField(blank=True, default=list)),
                ("total_experience_years", models.FloatField(default=0)),
                ("experience_details", models.JSONField(blank=True, default=list)),
                ("extracted_skills", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                (
                    "embedding_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("is_indexed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("parsing", "Parsing"),
                            ("parsed", "Parsed"),
                            ("indexed", "Indexed in Vector Store"),
                            ("failed", "Parsing Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("parse_error", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="users.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resumes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeParseLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("message", models.TextField(blank=True)),
                ("processing_time_ms", models.IntegerField(default=0)),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parse_logs",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_parse_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("proficiency", models.CharField(blank=True, max_length=50)),
                ("years_used", models.FloatField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_skills",
            },
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["company", "status"], name="resumes_company_e3a597_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["candidate_email"], name="resumes_candida_d6fa63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["is_active", "company"], name="resumes_is_acti_a8aacf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(fields=["deleted"], name="resumes_deleted_7a0d77_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="resumeskill",
            unique_together={("resume", "name")},
        ),
    ]
