# """
# Django settings for config project.

# Generated by 'django-admin startproject' using Django 5.2.5.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/      

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# import os
# from pathlib import Path
# from dotenv import load_dotenv
# from datetime import timedelta


# load_dotenv()


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-u%_iw8x708r=a(-xg+jr!5&2zni=(+4ws453(tvwaseclie1e@'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get('DEBUG')

# ALLOWED_HOSTS = ['*']

# AUTH_USER_MODEL = 'users.User'

# BACKEND_BASE_URL = os.environ.get('BACKEND_BASE_URL')
# MAX_RETRIES = 3
# RETRY_DELAY = 3
# FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL')
# PASSWORD_RESET_VALIDITY = 3
# PASSWORD_MIN_LENGTH = 8
# AUCTION_START_TIME_DELAY = 20 #mins
# FRONTEND_EMAIL_LINK = f"{FRONTEND_BASE_URL}/verify-link"



# INSTALLED_APPS = [
#     'django.contrib.contenttypes',  # ← MUST be first
#     'django.contrib.auth',          # ← Before admin
#     'apps.users',                   # ← Your custom user model BEFORE admin
#     'django.contrib.admin',         # ← After your users app
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',

#     'rest_framework',
#     'rest_framework_simplejwt.token_blacklist',
#     'django_celery_results',

#     'corsheaders',
#     'apps.myapp',
#     'apps.notification',
#     'apps.images',
    
#     'apps.jobs',
#     'apps.resumes',
#     'apps.screening',

#     "drf_spectacular",
#     "drf_spectacular_sidecar",
#     "django_ckeditor_5",
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'config.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': ['templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'config.wsgi.application'


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('POSTGRES_DB'),
#         'USER': os.environ.get('POSTGRES_USER'),
#         'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
#         'HOST': os.environ.get('POSTGRES_HOST'),
#         'PORT': os.environ.get('POSTGRES_PORT'),
#     }
# }


# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]



# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'static'
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://localhost:5173",
# ]

# REST_FRAMEWORK = {
    
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated'
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'utils.authenticate.CustomAuthentication',
#     ),
#     'DATETIME_FORMAT': "%Y-%m-%d %H:%M:%S",

#     "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
# }

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = os.environ.get("EMAIL_HOST")
# EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS")
# EMAIL_PORT = os.environ.get("EMAIL_PORT")
# EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")

# CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')
# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'

# # CELERY_TIMEZONE = 'UTC'
# # CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# MAX_LOGIN_ATTEMPTS = 8


# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(hours=10),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=15),
#     'ROTATE_REFRESH_TOKENS': False,
#     'BLACKLIST_AFTER_ROTATION': False,
#     'UPDATE_LAST_LOGIN': False,

#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': SECRET_KEY,
#     'VERIFYING_KEY': None,
#     'AUDIENCE': None,
#     'ISSUER': None,

#     'AUTH_HEADER_TYPES': ('Bearer',),
#     'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'user_id',
#     'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

#     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
#     'TOKEN_TYPE_CLAIM': 'token_type',

#     'JTI_CLAIM': 'jti',

#     'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
#     'SLIDING_TOKEN_LIFETIME': timedelta(days=23),
#     'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=23),

#     'AUTH_ACCESS_COOKIE': 'access_token',  # Cookie name. Enables cookies if value is set.
#     'AUTH_REFRESH_COOKIE': 'refresh_token',  # Cookie name. Enables cookies if value is set.
#     'AUTH_CSRF_ACCESS_COOKIE': 'csrf_access_token',  # Cookie name. Enables cookies if value is set.
#     'AUTH_CSRF_REFRESH_COOKIE': 'csrf_refresh_token',  # Cookie name. Enables cookies if value is set.
#     'AUTH_COOKIE_DOMAIN': None,  # A string like "example.com", or None for standard domain cookie.
#     'AUTH_COOKIE_SECURE': True,  # Whether the auth cookies should be secure (https:// only).
#     'AUTH_COOKIE_HTTP_ONLY': True,  # Http only cookie flag.It's not fetch by javascript.
#     'AUTH_COOKIE_PATH': '/',  # The path of the auth cookie.
#     'AUTH_COOKIE_SAMESITE': 'Lax',  # Whether to set the flag restricting cookie leaks on cross-site requests.
#                                     # This can be 'Lax', 'Strict', or None to disable the flag.
# }

# # settings.py
# CKEDITOR_5_CONFIGS = {
#     'default': {
#         'toolbar': ['heading', '|', 'bold', 'italic', 'link',
#                     'bulletedList', 'numberedList', 'blockQuote', 'imageUpload'],
#     },
#     'extends': {
#         'blockToolbar': [
#             'paragraph', 'heading1', 'heading2', 'heading3',
#             '|',
#             'bulletedList', 'numberedList',
#             '|',
#             'blockQuote',
#             'imageUpload'  # Added image upload to block toolbar
#         ],
#         'toolbar': [
#             'heading', '|', 
#             'outdent', 'indent', '|', 
#             'bold', 'italic', 'link', 'underline', 'strikethrough',
#             'code', 'subscript', 'superscript', 'highlight', '|', 
#             'codeBlock', 'sourceEditing', 'insertImage',
#             'bulletedList', 'numberedList', 'todoList', '|', 
#             'blockQuote', 'imageUpload', '|',
#             'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 
#             'mediaEmbed', 'removeFormat', 'insertTable',
#         ],
#         'image': {
#             'toolbar': [
#                 'imageTextAlternative', '|', 
#                 'imageStyle:alignLeft', 'imageStyle:alignRight', 
#                 'imageStyle:alignCenter', 'imageStyle:side', '|',
#                 'toggleImageCaption', 'imageTextAlternative'  # Added more options
#             ],
#             'styles': [
#                 'full',
#                 'side',
#                 'alignLeft',
#                 'alignRight',
#                 'alignCenter',
#             ]
#         },
#         'table': {
#             'contentToolbar': [
#                 'tableColumn', 'tableRow', 'mergeTableCells',
#                 'tableProperties', 'tableCellProperties'
#             ],
#             'tableProperties': {
#                 'borderColors': 'custom',
#                 'backgroundColors': 'custom'
#             },
#             'tableCellProperties': {
#                 'borderColors': 'custom',
#                 'backgroundColors': 'custom'
#             }
#         },
#         'heading': {
#             'options': [
#                 {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
#                 {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
#                 {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
#                 {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},
#                 {'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4'}  # Added H4
#             ]
#         },
#         'language': 'en',  # Explicitly set language
#         'htmlSupport': {  # Added HTML support for better compatibility
#             'allow': [
#                 {'name': '/.*/', 'attributes': True, 'classes': True, 'styles': True}
#             ]
#         }
#     }
# }






"""
Django settings for config project.
All sensitive/configurable values are read from the .env file.
No passwords, secrets, or API keys are hardcoded here.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# ─────────────────────────────────────────────────────────────────
#  BASE
# ─────────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent

# Pulled from .env — never hardcoded
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG      = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.User'

BACKEND_BASE_URL    = os.environ.get('BACKEND_BASE_URL')
FRONTEND_BASE_URL   = os.environ.get('FRONTEND_BASE_URL')
FRONTEND_EMAIL_LINK = f"{FRONTEND_BASE_URL}/verify-link"

MAX_RETRIES              = 3
RETRY_DELAY              = 3
AUCTION_START_TIME_DELAY = 20   # mins

# These come from .env
PASSWORD_RESET_VALIDITY = int(os.environ.get('PASSWORD_RESET_VALIDITY', 3))
PASSWORD_MIN_LENGTH     = 8
MAX_LOGIN_ATTEMPTS      = int(os.environ.get('MAX_LOGIN_ATTEMPTS', 5))
LINK_TOKEN_LENGTH       = int(os.environ.get('LINK_TOKEN_LENGTH', 32))


# ─────────────────────────────────────────────────────────────────
#  INSTALLED APPS
# ─────────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'apps.users',           # custom user model — must come before admin
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_celery_results',
    'django_celery_beat',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django_ckeditor_5',

    # Existing apps
    'apps.notification',
    'apps.images',

    # New RAG apps
    'apps.jobs',
    'apps.resumes',
    'apps.screening',
]


# ─────────────────────────────────────────────────────────────────
#  MIDDLEWARE
# ─────────────────────────────────────────────────────────────────
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ─────────────────────────────────────────────────────────────────
#  DATABASE  (all values from .env)
# ─────────────────────────────────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.postgresql',
        'NAME':     os.environ.get('POSTGRES_DB'),
        'USER':     os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST':     os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT':     os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# ─────────────────────────────────────────────────────────────────
#  AUTH PASSWORD VALIDATORS
# ─────────────────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ─────────────────────────────────────────────────────────────────
#  INTERNATIONALISATION
# ─────────────────────────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = os.environ.get('TIME_ZONE', 'UTC')   # e.g. Asia/Karachi
USE_I18N      = True
USE_TZ        = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ─────────────────────────────────────────────────────────────────
#  STATIC & MEDIA
# ─────────────────────────────────────────────────────────────────
STATIC_URL  = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_URL   = '/media/'
MEDIA_ROOT  = BASE_DIR / 'media'

# Max resume upload size (10 MB)
MAX_UPLOAD_SIZE = 10 * 1024 * 1024


# ─────────────────────────────────────────────────────────────────
#  CORS
# ─────────────────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
]


# ─────────────────────────────────────────────────────────────────
#  REST FRAMEWORK
# ─────────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'utils.authenticate.CustomAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DATETIME_FORMAT': "%Y-%m-%d %H:%M:%S",
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'apps.core.utils.exception_handler.custom_exception_handler',
}


# ─────────────────────────────────────────────────────────────────
#  EMAIL  (all values from .env)
# ─────────────────────────────────────────────────────────────────
EMAIL_BACKEND       = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST          = os.environ.get("EMAIL_HOST")
EMAIL_USE_TLS       = os.environ.get("EMAIL_USE_TLS", "True").lower() in ('true', '1', 'yes')
EMAIL_PORT          = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_HOST_USER     = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")


# ─────────────────────────────────────────────────────────────────
#  CELERY  (RabbitMQ broker — from .env)
# ─────────────────────────────────────────────────────────────────
CELERY_BROKER_URL        = os.environ.get('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND    = 'django-db'
CELERY_ACCEPT_CONTENT    = ['application/json']
CELERY_TASK_SERIALIZER   = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE          = os.environ.get('TIME_ZONE', 'UTC')
CELERY_TASK_TIME_LIMIT   = 30 * 60    # 30 min — covers long AI screening tasks
CELERY_BEAT_SCHEDULER    = 'django_celery_beat.schedulers:DatabaseScheduler'


# ─────────────────────────────────────────────────────────────────
#  SIMPLE JWT
# ─────────────────────────────────────────────────────────────────
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(hours=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=15),
    'ROTATE_REFRESH_TOKENS':  False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM':     'HS256',
    'SIGNING_KEY':   SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE':      None,
    'ISSUER':        None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME':  'HTTP_AUTHORIZATION',
    'USER_ID_FIELD':     'id',
    'USER_ID_CLAIM':     'user_id',
    'USER_AUTHENTICATION_RULE':
        'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM':   'token_type',
    'JTI_CLAIM':          'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM':  'refresh_exp',
    'SLIDING_TOKEN_LIFETIME':           timedelta(days=23),
    'SLIDING_TOKEN_REFRESH_LIFETIME':   timedelta(days=23),

    'AUTH_ACCESS_COOKIE':       'access_token',
    'AUTH_REFRESH_COOKIE':      'refresh_token',
    'AUTH_CSRF_ACCESS_COOKIE':  'csrf_access_token',
    'AUTH_CSRF_REFRESH_COOKIE': 'csrf_refresh_token',
    'AUTH_COOKIE_DOMAIN':       None,
    'AUTH_COOKIE_SECURE':       True,
    'AUTH_COOKIE_HTTP_ONLY':    True,
    'AUTH_COOKIE_PATH':         '/',
    'AUTH_COOKIE_SAMESITE':     'Lax',
}


# ─────────────────────────────────────────────────────────────────
#  DRF SPECTACULAR
# ─────────────────────────────────────────────────────────────────
SPECTACULAR_SETTINGS = {
    'TITLE':       'AI Resume Screener API',
    'DESCRIPTION': 'Multi-agent RAG-powered resume screening system',
    'VERSION':     '1.0.0',
}


# ─────────────────────────────────────────────────────────────────
#  GROQ LLM  (from .env — replaces OpenAI)
# ─────────────────────────────────────────────────────────────────
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_MODEL   = os.environ.get('GROQ_MODEL', 'llama-3.1-8b-instant')


# ─────────────────────────────────────────────────────────────────
#  EMBEDDINGS  (sentence-transformers, runs locally — no API key)
# ─────────────────────────────────────────────────────────────────
EMBEDDING_MODEL     = os.environ.get('EMBEDDING_MODEL', 'sentence-transformers/all-MiniLM-L6-v2')
EMBEDDING_DIMENSION = int(os.environ.get('EMBEDDING_DIMENSION', 384))


# ─────────────────────────────────────────────────────────────────
#  CHROMADB  (from .env)
# ─────────────────────────────────────────────────────────────────
VECTOR_STORE_TYPE        = os.environ.get('VECTOR_STORE_TYPE', 'chromadb')
CHROMADB_PERSIST_DIR     = os.environ.get('CHROMA_PERSIST_DIR', str(BASE_DIR / 'chroma_db'))
CHROMADB_COLLECTION_NAME = os.environ.get('CHROMADB_COLLECTION_NAME', 'rag_documents')
CHROMA_RESUME_COLLECTION = 'resumes'
CHROMA_JD_COLLECTION     = 'job_descriptions'


# ─────────────────────────────────────────────────────────────────
#  WEB SEARCH — Tavily  (from .env)
# ─────────────────────────────────────────────────────────────────
TAVILY_API_KEY = os.environ.get('TAVILY_API_KEY', '')
USE_WEB_SEARCH = os.environ.get('USE_WEB_SEARCH', 'True').lower() in ('true', '1', 'yes')


# ─────────────────────────────────────────────────────────────────
#  AGENT CONFIGURATION  (from .env)
# ─────────────────────────────────────────────────────────────────
MAX_AGENT_ITERATIONS = int(os.environ.get('MAX_AGENT_ITERATIONS', 10))
AGENT_TIMEOUT        = int(os.environ.get('AGENT_TIMEOUT', 60))
USE_LANGGRAPH        = os.environ.get('USE_LANGGRAPH', 'True').lower() in ('true', '1', 'yes')


# ─────────────────────────────────────────────────────────────────
#  RAG PARAMETERS  (from .env)
# ─────────────────────────────────────────────────────────────────
CHUNK_SIZE          = int(os.environ.get('CHUNK_SIZE', 800))
CHUNK_OVERLAP       = int(os.environ.get('CHUNK_OVERLAP', 100))
TOP_K_RESULTS       = int(os.environ.get('TOP_K_RESULTS', 5))
RELEVANCE_THRESHOLD = float(os.environ.get('RELEVANCE_THRESHOLD', 0.3))


# ─────────────────────────────────────────────────────────────────
#  LOGGING  (from .env)
# ─────────────────────────────────────────────────────────────────
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class':     'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level':    LOG_LEVEL,
    },
    'loggers': {
        'django': {'handlers': ['console'], 'level': LOG_LEVEL, 'propagate': False},
        'core':   {'handlers': ['console'], 'level': LOG_LEVEL, 'propagate': False},
        'apps':   {'handlers': ['console'], 'level': LOG_LEVEL, 'propagate': False},
    },
}


# ─────────────────────────────────────────────────────────────────
#  CKEDITOR 5
# ─────────────────────────────────────────────────────────────────
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload'],
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|', 'bulletedList', 'numberedList', '|',
            'blockQuote', 'imageUpload',
        ],
        'toolbar': [
            'heading', '|', 'outdent', 'indent', '|',
            'bold', 'italic', 'link', 'underline', 'strikethrough',
            'code', 'subscript', 'superscript', 'highlight', '|',
            'codeBlock', 'sourceEditing', 'insertImage',
            'bulletedList', 'numberedList', 'todoList', '|',
            'blockQuote', 'imageUpload', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor',
            'mediaEmbed', 'removeFormat', 'insertTable',
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:alignRight',
                'imageStyle:alignCenter', 'imageStyle:side', '|',
                'toggleImageCaption', 'imageTextAlternative',
            ],
            'styles': ['full', 'side', 'alignLeft', 'alignRight', 'alignCenter'],
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties',
            ],
            'tableProperties':     {'borderColors': 'custom', 'backgroundColors': 'custom'},
            'tableCellProperties': {'borderColors': 'custom', 'backgroundColors': 'custom'},
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph',  'class': 'ck-heading_paragraph'},
                {'model': 'heading1',  'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2',  'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3',  'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},
                {'model': 'heading4',  'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4'},
            ],
        },
        'language':    'en',
        'htmlSupport': {
            'allow': [{'name': '/.*/', 'attributes': True, 'classes': True, 'styles': True}],
        },
    },
}