# Generated by Django 5.2.5 on 2026-03-15 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_remote", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("responsibilities", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("nice_to_have", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("intern", "Intern"),
                            ("junior", "Junior (0-2 yrs)"),
                            ("mid", "Mid-Level (2-5 yrs)"),
                            ("senior", "Senior (5-8 yrs)"),
                            ("lead", "Lead (8+ yrs)"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("min_experience_years", models.FloatField(default=0)),
                ("max_experience_years", models.FloatField(blank=True, null=True)),
                (
                    "education_requirement",
                    models.CharField(
                        blank=True,
                        help_text="e.g. bachelor, master, any",
                        max_length=100,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=5)),
                ("extracted_skills", models.JSONField(blank=True, default=list)),
                ("extracted_keywords", models.JSONField(blank=True, default=list)),
                ("embedding_id", models.CharField(blank=True, max_length=255)),
                ("weight_skills", models.FloatField(default=0.35)),
                ("weight_experience", models.FloatField(default=0.3)),
                ("weight_education", models.FloatField(default=0.2)),
                ("weight_fit", models.FloatField(default=0.15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("screening_count", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_descriptions",
                        to="users.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job_descriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobAnalysis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("key_requirements", models.TextField(blank=True)),
                ("ideal_candidate_profile", models.TextField(blank=True)),
                ("technical_stack", models.JSONField(default=list)),
                ("soft_skills", models.JSONField(default=list)),
                ("domain_knowledge", models.JSONField(default=list)),
                ("red_flags", models.JSONField(default=list)),
                ("seniority_level", models.CharField(blank=True, max_length=30)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="jobs.jobdescription",
                    ),
                ),
            ],
            options={
                "db_table": "job_analyses",
            },
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=50)),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("nice_to_have", "Nice to Have"),
                            ("preferred", "Preferred"),
                            ("required", "Required"),
                            ("must_have", "Must Have"),
                        ],
                        default="required",
                        max_length=20,
                    ),
                ),
                ("years_required", models.FloatField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="jobs.jobdescription",
                    ),
                ),
            ],
            options={
                "db_table": "job_skills",
            },
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(
                fields=["status", "company"], name="job_descrip_status_e7de7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(fields=["title"], name="job_descrip_title_869c66_idx"),
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(
                fields=["deleted"], name="job_descrip_deleted_5599a3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobskill",
            unique_together={("job", "name")},
        ),
    ]
