# Generated by Django 5.2.5 on 2026-03-27 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("resumes", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_resumes", models.PositiveIntegerField(default=0)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("pass_threshold", models.FloatField(default=70.0)),
                ("top_n_candidates", models.PositiveIntegerField(default=10)),
                ("total_tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_sessions",
                        to="users.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_screenings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_sessions",
                        to="jobs.jobdescription",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "screening_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_score", models.FloatField(default=0)),
                ("skill_score", models.FloatField(default=0)),
                ("experience_score", models.FloatField(default=0)),
                ("education_score", models.FloatField(default=0)),
                ("fit_score", models.FloatField(default=0)),
                ("semantic_similarity", models.FloatField(default=0)),
                ("matched_skills", models.JSONField(blank=True, default=list)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("bonus_skills", models.JSONField(blank=True, default=list)),
                ("must_have_skills_met", models.BooleanField(default=False)),
                ("years_of_experience", models.FloatField(default=0)),
                ("experience_gap_years", models.FloatField(default=0)),
                ("relevant_experience_pct", models.FloatField(default=0)),
                ("education_match", models.BooleanField(default=False)),
                ("education_level", models.CharField(blank=True, max_length=30)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("explanation", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("interview_questions", models.JSONField(blank=True, default=list)),
                ("red_flags", models.JSONField(blank=True, default=list)),
                ("growth_potential", models.TextField(blank=True)),
                (
                    "ai_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("shortlisted", "Shortlisted"),
                            ("interview", "Invite to Interview"),
                            ("maybe", "Maybe"),
                            ("hold", "On Hold"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "human_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("shortlisted", "Shortlisted"),
                            ("interview", "Invite to Interview"),
                            ("maybe", "Maybe"),
                            ("hold", "On Hold"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("human_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("processing_time_ms", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_results",
                        to="jobs.jobdescription",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_results",
                        to="resumes.resume",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="screening.screeningsession",
                    ),
                ),
            ],
            options={
                "db_table": "screening_results",
                "ordering": ["-overall_score"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecutionLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("resume_parser", "Resume Parser Agent"),
                            ("jd_analyzer", "JD Analyzer Agent"),
                            ("skill_matcher", "Skill Matcher Agent"),
                            ("experience_scorer", "Experience Scorer Agent"),
                            ("education_scorer", "Education Scorer Agent"),
                            ("rag_retriever", "RAG Retriever Agent"),
                            ("explanation", "Explanation Agent"),
                            ("orchestrator", "Orchestrator"),
                        ],
                        max_length=30,
                    ),
                ),
                ("agent_version", models.CharField(default="1.0", max_length=10)),
                ("input_summary", models.JSONField(blank=True, default=dict)),
                ("output_summary", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("processing_time_ms", models.PositiveIntegerField(default=0)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                (
                    "screening_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_logs",
                        to="screening.screeningresult",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_logs",
                        to="screening.screeningsession",
                    ),
                ),
            ],
            options={
                "db_table": "agent_execution_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="screeningsession",
            index=models.Index(
                fields=["job", "status"], name="screening_s_job_id_3ecb26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="screeningsession",
            index=models.Index(
                fields=["company", "status"], name="screening_s_company_c8a465_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="screeningsession",
            index=models.Index(
                fields=["deleted"], name="screening_s_deleted_61c226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="screeningresult",
            index=models.Index(
                fields=["session", "overall_score"],
                name="screening_r_session_08fdee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="screeningresult",
            index=models.Index(
                fields=["job", "overall_score"], name="screening_r_job_id_fa2bf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="screeningresult",
            index=models.Index(
                fields=["ai_decision"], name="screening_r_ai_deci_d9f27e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="screeningresult",
            index=models.Index(
                fields=["deleted"], name="screening_r_deleted_6c9f33_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="screeningresult",
            unique_together={("session", "resume")},
        ),
    ]
