# Generated by Django 5.2.5 on 2026-03-27 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RerankCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("document_hash", models.CharField(db_index=True, max_length=64)),
                ("score", models.FloatField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ragstack_rerank_cache",
            },
        ),
        migrations.CreateModel(
            name="UsageMetrics",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("queries_count", models.IntegerField(default=0)),
                ("documents_uploaded", models.IntegerField(default=0)),
                ("chunks_processed", models.IntegerField(default=0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("avg_confidence_score", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "ragstack_usage_metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("message_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ragstack_conversations",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("content_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("chunks_count", models.IntegerField(default=0)),
                ("entities_count", models.IntegerField(default=0)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accessible_rag_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ragstack_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("chunk_index", models.IntegerField()),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("word_count", models.IntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="ragstack.document",
                    ),
                ),
            ],
            options={
                "db_table": "ragstack_document_chunks",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="GraphEntity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "source_documents",
                    models.ManyToManyField(
                        related_name="entities", to="ragstack.document"
                    ),
                ),
            ],
            options={
                "db_table": "ragstack_graph_entities",
            },
        ),
        migrations.CreateModel(
            name="GraphRelationship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relation_type", models.CharField(db_index=True, max_length=100)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("weight", models.FloatField(default=1.0)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="ragstack.graphentity",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="ragstack.graphentity",
                    ),
                ),
            ],
            options={
                "db_table": "ragstack_graph_relationships",
            },
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField()),
                ("rewritten_query", models.TextField(blank=True)),
                ("answer", models.TextField()),
                (
                    "strategy_used",
                    models.CharField(
                        choices=[
                            ("simple", "Simple RAG"),
                            ("hybrid", "Hybrid Search"),
                            ("rerank", "Re-ranked"),
                            ("agentic", "Agentic RAG"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("retrieved_chunks", models.JSONField(blank=True, default=list)),
                ("processing_time", models.FloatField()),
                ("retrieval_time", models.FloatField(default=0.0)),
                ("rerank_time", models.FloatField(default=0.0)),
                ("generation_time", models.FloatField(default=0.0)),
                ("used_reranking", models.BooleanField(default=False)),
                ("used_query_rewriting", models.BooleanField(default=False)),
                ("hybrid_search_alpha", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="ragstack.conversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_documents",
                    models.ManyToManyField(
                        related_name="queries", to="ragstack.document"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ragstack_queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quote", models.TextField()),
                ("relevance_score", models.FloatField()),
                ("position_in_answer", models.IntegerField()),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="ragstack.documentchunk",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="ragstack.query",
                    ),
                ),
            ],
            options={
                "db_table": "ragstack_citations",
                "ordering": ["query", "position_in_answer"],
            },
        ),
        migrations.CreateModel(
            name="QueryFeedback",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Fair"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("answer_helpful", models.BooleanField(blank=True, null=True)),
                ("sources_relevant", models.BooleanField(blank=True, null=True)),
                ("answer_accurate", models.BooleanField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "query",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="ragstack.query",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_feedback_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ragstack_query_feedback",
            },
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="ragstack_do_documen_05abe1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["content_hash"], name="ragstack_do_content_8458d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graphentity",
            index=models.Index(
                fields=["entity_type"], name="ragstack_gr_entity__b08455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graphentity",
            index=models.Index(fields=["name"], name="ragstack_gr_name_078058_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="graphrelationship",
            unique_together={("source", "target", "relation_type")},
        ),
    ]
